### PR TITLE
Add an option to the Splits to show two rows

### LINKED ISSUE #122: Implement 2 Row Mode for all the Components
livesplit-core has this now, but LSO doesn't render it yet.

### PR DESCRIPTION
**Pull request by wooferzfg**
Fix #122

### CODE REVIEW

**Comment by CryZe** [comment]
Other than the icons not increasing their size, this seems perfect.

**Comment by CryZe** [comment]
And I guess the bouncing again:

**Comment by wooferzfg** [comment]
The bouncing is still the same issue as before, so I'm not sure how we can resolve it.

I'll update the icon height to match the full height when displaying two rows.

**Comment by CryZe** [comment]
Can we just use position: absolute for the thicker line or so, such that it doesn't affect the layout of the rest?

**Comment by CryZe** [comment]
@wooferzfg I pushed some fix for the increased icon size. Can you check if it looks good to you?

**Comment by wooferzfg** [comment]
I tried to get rid of the "bouncing" but it makes things look weird and cut off.

Current implementation:

chrome_vJvotkv2kJ

With the "bouncing" fix:

chrome_O7kf0iVaKt

I think we should just keep what we have for now.

**Comment by wooferzfg** [comment]
Besides that, this PR looks good to me now. Feel free to merge if you think it's ready.

**Pull request merged**
