### PR TITLE
Always show the sidebar when the screen is wide enough

### PR DESCRIPTION
**Pull request by wooferzfg**

### CODE REVIEW

**Comment by CryZe** [comment]
I have yet to try this branch myself. However I think we really should try to replace the sidebar entirely, as it doesn't work at all on iOS anymore #129

**Comment by wooferzfg** [comment]
Could we just have a button open the sidebar instead of relying only on swiping?

**Comment by CryZe** [comment]
Yeah I guess that's okay. It should probably hover in the bottom left corner and only when not in desktop mode or so.

**Comment by wooferzfg** [comment]
I agree that we need to completely rework our layout for mobile. The editors are especially hard to use because you constantly have to scroll. If we implement mobile apps with something like Flutter or React Native, we need to think about how we should maintain both the web and app versions.

For now though, I added a floating button to open the sidebar. This button only shows up when your screen isn't wide enough to show the sidebar by default. In my opinion, it's at least a good temporary improvement over what we currently have.

**Comment by CryZe** [comment]
I just tried this. Is there a reason we are going with it being pinned to the right instead of the left?

**Comment by CryZe** [comment]
Additionally we should modify our margins of the different views to be the same as the layout editor (which apparently has larger margins).

**Pull request merged**
