### PR TITLE
Make minor fixes to the webkit scrollbars.

### PR DESCRIPTION
**Pull request by TheEssenceOfDarkness**
Noticed a couple of minor tweaks could be made here.

### CODE REVIEW

**Comment by TheEssenceOfDarkness** [comment]
I just resolved a merge conflict due to the recent change to split up the CSS so this should be good to merge now.

**Comment by CryZe** [comment]
If there's even anything that can be done about this.

**Comment by TheEssenceOfDarkness** [comment]
>I'm getting some weird white square in the bottom right when both scrollbars are visible.

I probably forgot to copy that over when fixing the merge conflict. I have no idea how that happened.

**Comment by CryZe** [comment]
Well there's still a visible square:

**Pull request merged**
