### PR TITLE
Add support for custom variables

### PR DESCRIPTION
**Pull request by wooferzfg**
This PR uses the changes in https://github.com/LiveSplit/livesplit-core/pull/201

For now, I added the ability to add a custom variable and modify a custom variable. The bindings don't currently have a way to remove a custom variable, so I guess that would have to be added first before I can add removal functionality. I'm also not sure exactly how we'll handle removal because the Settings component doesn't currently support anything like that.

We also want components to be able to display custom variables, but I guess that can come later as well.

### CODE REVIEW

**Comment by CryZe** [comment]
> We also want components to be able to display custom variables, but I guess that can come later as well.

Doesn't the text component already support showing them? Pretty sure that's like the first thing I implemented.

**Comment by wooferzfg** [comment]
Oops, you're right. I didn't notice the "Use Variable" option before for some reason.

**Comment by CryZe** [comment]
This seems to delete a bunch of stuff. You probably should've tried rebasing the lsc branch instead of deleting stuff here. I'll try to fix it.

**Comment by CryZe** [comment]
I added removing the variables to the C API.

**Comment by wooferzfg** [comment]
Thanks for doing that + rebasing the branch in livesplit-core. I temporarily removed stuff like the Segment Time component because it would be easy to put back later and I didn't want to deal with the rebase, but now all that's done :grinning: 

I'll work on adding a delete button for each variable next.

**Comment by wooferzfg** [comment]
I added the ability to remove custom variables. This involved a refactor of `Settings.tsx` to use a new interface, `ExtendedSettingsDescriptionJson`, that is an extension of the `SettingsDescriptionJson` defined by `livesplit-core`. This allows us to define additional types of settings that are exclusive to LiveSplit One without needing to modify `livesplit-core`.

**Comment by CryZe** [comment]
Nice, I‘ll take a look when I‘m back from vacation (on the 2nd)

**Comment by CryZe** [comment]
It seems like we don't show any information on the variables tab at all until the speedrun.com information resolved, which means you can't use custom variables for games that are not on speedrun.com (or the name just doesn't match).

**Pull request merged**
